import type { Metadata } from "next";
import {Crimson_Text, DM_Sans, Roboto_Mono, Rethink_Sans,  Reddit_Mono, } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import { Footer, Navbar } from "@/components";

const crimson = Crimson_Text({
  variable: "--font-crimson",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const rethinkSans = Rethink_Sans({
  variable: "--font-rethink-sans",
  subsets: ["latin"],
});

const redditMono = Reddit_Mono({
  variable: "--font-reddit-mono",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Browse Anything by Area",
  description: "Generated by created br OreO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${rethinkSans.variable}  ${redditMono.variable} ${crimson.variable} ${robotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
